use commands::{
    common::{
        calculate_non_duress_output, multisig::open_multisig_wallet_non_interactive,
        singlesig::open_singlesig_wallet_non_interactive,
    },
    generate::DuressPublicInfoParams,
};
use path_absolutize::*;
use std::{
    borrow::Cow,
    path::{Path, PathBuf},
    str::FromStr,
    sync::{Arc, Mutex},
    thread::JoinHandle,
    time::Instant,
};

use frozenkrill_core::{
    DEFAULT_MAX_ADDITIONAL_PADDING, DEFAULT_MIN_ADDITIONAL_PADDING, PaddingParams,
    anyhow::{self, Context, bail},
    bip39::{self, Language, Mnemonic},
    bitcoin::{
        Network,
        secp256k1::{All, Secp256k1},
    },
    custom_logger,
    key_derivation::{self, KeyDerivationDifficulty, default_derive_key},
    log, mnemonic_utils, parse_keyfiles_paths, rand,
    rand_core::CryptoRng,
    random_generation_utils::get_secp,
    wallet_description::{EncryptedWalletVersion, KEY_SIZE, MultisigType, SALT_SIZE, ScriptType},
};

use clap::{Parser, Subcommand};

use dialoguer::{
    Confirm,
    console::Term,
    theme::{ColorfulTheme, SimpleTheme, Theme},
};
use frozenkrill_core::secrecy::{ExposeSecret, SecretBox, SecretString};
use indicatif::ProgressBar;

use frozenkrill_core::wallet_description::{
    SingleSigWalletDescriptionV0, SinglesigJsonWalletDescriptionV0, WordCount,
};

use crate::progress_bar::get_spinner;

mod commands;
mod progress_bar;

type Secret<T> = SecretBox<T>;

const VERSION: &str = "0.0.0";

const PASSWORD_ENV: &str = "PASSWORD";

const PASSWORD_HELP: &str =
    "Password used to encrypt the file. If not given, a prompt will ask for one";

const KEYFILE_HELP: &str = "Files to be used for a complementary 'password'. Can be given multiple times. Multiple files and directories are allowed. Directories are followed recursively";
const ENABLE_DURESS_WALLET: &str = "Will enable plausible deniability making the default wallet password a duress one (i.e to be used under coercion)";
const INPUT_WALLET_HELP: &str =
    "The encrypted wallet previously generated by the 'generate' command";
const USE_12_WORDS_HELP: &str = "Use 12 words for the seed phrase instead of the default 24";
const USE_TESTNET_HELP: &str = "Derive addresses and keys for testnet instead of mainnet";
const ADDRESSES_QUANTITY_HELP: &str = "How many addresses to export on public info json";
const DIFFICULTY_HELP: &str = {
    const EASY: KeyDerivationDifficulty = KeyDerivationDifficulty::Easy;
    const EASY_TIME: &str = EASY.estimate_time();
    const EASY_MEMORY: &str = EASY.estimate_memory();
    const NORMAL: KeyDerivationDifficulty = KeyDerivationDifficulty::Normal;
    const NORMAL_TIME: &str = NORMAL.estimate_time();
    const NORMAL_MEMORY: &str = NORMAL.estimate_memory();
    const HARD: KeyDerivationDifficulty = KeyDerivationDifficulty::Hard;
    const HARD_TIME: &str = HARD.estimate_time();
    const HARD_MEMORY: &str = HARD.estimate_memory();
    const VERYHARD: KeyDerivationDifficulty = KeyDerivationDifficulty::VeryHard;
    const VERYHARD_TIME: &str = VERYHARD.estimate_time();
    const VERYHARD_MEMORY: &str = VERYHARD.estimate_memory();
    const_format::formatcp!("How hard is to derive the key.
More specifically, how much cpu (time) and ram memory (space) argon2id will require. Time depends on the platform, but roughly we have:
--difficulty easy: {EASY_TIME}, {EASY_MEMORY}
--difficulty normal: {NORMAL_TIME}, {NORMAL_MEMORY} (the default)
--difficulty hard: {HARD_TIME}, {HARD_MEMORY}
--difficulty veryhard: {VERYHARD_TIME}, {VERYHARD_MEMORY}
To open a encrypted wallet you need to specify the same difficulty used to generate it. If in doubt, leave the default
")
};

const USER_GENERATED_SEED_HELP: &str =
    "Instead of randomly generating the seed, will ask the user to manually input the words";

const ALWAYS_HIDE_TYPED_SEED_HELP: &str = "When --user-generated-seed is used and the user chose to type 12/24 words, the previous typed words will be hidden.
Note: if the user is typing 11/23 words this is already the behavior";

const WALLET_OUTPUT_FILE_HELP: &str = "Where to save the generated encrypted wallet. Any file name is valid as long the file doesn't exists";

const PUBLIC_INFO_JSON_OUTPUT_HELP: &str = "Name of the file to export public parameters and addresses of the wallet into. Useful to import on hot wallets";

const WALLET_FILE_TYPE_HELP: &str = r#"Pick between a 'standard' or a 'compact' wallet.
The standard one will include all metadata required to describe the wallet, while the compact one will only save the encrypted entropy and will rely on implicit standard and conventions.
Use the compact only if you need to save bytes (for instance, to put the wallet in a QR code)"#;

#[derive(clap::Args)]
#[command(
    arg_required_else_help = true,
    about = "Generate a singlesig encrypted wallet"
)]
struct SinglesigGenerateArgs {
    #[clap(flatten)]
    common: GenerateCommon,
    #[clap(
        long,
        action,
        help = USE_12_WORDS_HELP
    )]
    use_12_words: bool,
    #[clap(
        long,
        action,
        help = ENABLE_DURESS_WALLET
    )]
    enable_duress_wallet: bool,
    #[clap(
        long,
        action,
        help = USER_GENERATED_SEED_HELP
    )]
    user_generated_seed: bool,
    #[clap(
        long,
        action,
        help = ALWAYS_HIDE_TYPED_SEED_HELP
    )]
    always_hide_typed_seed: bool,
    #[clap(
        help = WALLET_OUTPUT_FILE_HELP
    )]
    wallet_output_file: Option<String>,
    #[clap(
        help = PUBLIC_INFO_JSON_OUTPUT_HELP
    )]
    public_info_json_output: Option<String>,
}

#[derive(clap::Args)]
struct GenerateCommon {
    #[clap(
        long,
        action,
        help = "Disable all padding, the file will be as small as possible but now an attacker may infer something about its contents using the file size. Be careful, only use this if you know what you're doing"
    )]
    disable_all_padding: bool,
    #[clap(
        long,
        default_value_t = DEFAULT_MIN_ADDITIONAL_PADDING
    )]
    min_additional_padding_bytes: u32,
    #[clap(
        long,
        default_value_t = DEFAULT_MAX_ADDITIONAL_PADDING
    )]
    max_additional_padding_bytes: u32,
    #[clap(
        long,
        action,
        help = USE_TESTNET_HELP
    )]
    use_testnet: bool,
    #[clap(
        long,
        help = KEYFILE_HELP
    )]
    keyfile: Vec<String>,
    #[clap(
        long,
        help = DIFFICULTY_HELP,
        default_value_t = key_derivation::DEFAULT_DIFFICULTY_LEVEL
    )]
    difficulty: KeyDerivationDifficulty,
    #[clap(long, help = ADDRESSES_QUANTITY_HELP, default_value = "100")]
    addresses_quantity: u32,
    #[clap(long, help = WALLET_FILE_TYPE_HELP,
        default_value_t = WalletFileType::Standard)]
    wallet_file_type: WalletFileType,

    #[clap(
        long,
        env = PASSWORD_ENV,
        help = PASSWORD_HELP
    )]
    password: Option<String>,
}

#[derive(Clone, Copy)]
pub enum WalletFileType {
    Standard,
    Compact,
}
impl WalletFileType {
    pub fn to_encrypted_wallet_version(
        self,
        network: Network,
        script_type: ScriptType,
    ) -> anyhow::Result<EncryptedWalletVersion> {
        match self {
            Self::Standard => Ok(EncryptedWalletVersion::V0Standard),
            Self::Compact => match (network, script_type) {
                (Network::Bitcoin, ScriptType::SegwitNative) => {
                    Ok(EncryptedWalletVersion::V0CompactMainnet)
                }
                (Network::Testnet, ScriptType::SegwitNative) => {
                    Ok(EncryptedWalletVersion::V0CompactTestnet)
                }
                (other, ScriptType::SegwitNative) => {
                    bail!("Unsupported bitcoin network: {other:?}")
                }
            },
        }
    }
}
impl FromStr for WalletFileType {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_lowercase().as_str() {
            "standard" => Ok(Self::Standard),
            "compact" => Ok(Self::Compact),
            other => bail!("Got '{other}', it should be either 'standard' or 'compact'"),
        }
    }
}

impl std::fmt::Display for WalletFileType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WalletFileType::Standard => f.write_str("standard"),
            WalletFileType::Compact => f.write_str("compact"),
        }
    }
}

#[derive(clap::Args)]
#[command(
    arg_required_else_help = true,
    about = "Generate a multisig encrypted wallet"
)]
struct MultisigGenerateArgs {
    #[clap(flatten)]
    common: GenerateCommon,
    #[clap(help = "Multisig configuration to be used, like 2-of-3, 3-of-5, etc")]
    configuration: MultisigType,
    #[clap(
        long,
        help = WALLET_OUTPUT_FILE_HELP
    )]
    encrypted_wallet_output_file: Option<String>,
    #[clap(
        long,
        help = PUBLIC_INFO_JSON_OUTPUT_HELP
    )]
    json_output_file: Option<String>,
    #[clap(
        help = "Input wallets to use as signers/public keys. May be a encrypted wallet or just the json with public information (xpub, derivation path, etc)"
    )]
    input_files: Vec<String>,
}

#[derive(clap::Args)]
#[command(
    about = "Shows the seed and private key. It should only be used if you are going to move the funds to another wallet"
)]
struct SinglesigShowSecretsArgs {
    #[clap(
        long,
        action,
        help = "This flag is mandatory because the 'show-secrets' command will expose secrets and therefore should carefully be used in extraordinary circumstances"
    )]
    acknowledge_dangerous_operation: bool,
}

#[derive(clap::Args)]
#[command(about = "Show wallet contents")]
struct MultisigShowSecretsArgs {}

#[derive(clap::Args)]
struct CommonExportPublicInfoArgs {
    #[clap(long, help = ADDRESSES_QUANTITY_HELP, default_value = "100")]
    quantity: u32,
    #[clap(long, help = "Index of first address", default_value = "0")]
    first_index: u32,
    #[clap(help = "Destination JSON file")]
    output_file_json: Option<String>,
}

#[derive(clap::Args)]
#[command(
    about = "Export public parameters and addresses of the wallet. Useful to import on hot wallets"
)]
struct SinglesigExportPublicInfoArgs {
    #[clap(flatten)]
    common: CommonExportPublicInfoArgs,
    #[clap(help = "Destination non duress JSON file")]
    non_duress_output_file_json: Option<String>,
}

#[derive(clap::Args)]
#[command(about = "Export wallet info in json format")]
struct MultisigExportPublicInfoArgs {
    #[clap(flatten)]
    common: CommonExportPublicInfoArgs,
}

#[derive(clap::Args)]
#[command(about = "Show a receiving address QR Code by index")]
struct ShowReceivingQrCodeArgs {
    #[clap(
        help = "Which address to show. Zero is first address",
        default_value = "0"
    )]
    address_index: u32,
    #[clap(
        short,
        long,
        help = "Amount to receive in btc/satoshis, like '2.3 btc' or '1500 sats'"
    )]
    amount: Option<String>,
}

#[derive(clap::Args)]
#[command(about = "Sign a PSBT file")]
struct SignPsbtArgs {
    #[clap(help = "Input PSBT file (commonly with a .psbt extension)")]
    input_psbt_file: String,
    #[clap(help = "The output PSBT file with this wallet signature")]
    signed_output_psbt_file: Option<String>,
}

#[derive(clap::Args)]
#[command(about = "Reencode the wallet with new password and other parameters")]
struct SinglesigReencodeArgs {
    #[clap(flatten)]
    common: GenerateCommon,
    #[clap(
        help = WALLET_OUTPUT_FILE_HELP
    )]
    wallet_output_file: Option<String>,
}

#[derive(Subcommand)]
enum SinglesigOpenCommands {
    ShowSecrets(SinglesigShowSecretsArgs),
    ShowReceivingQrCode(ShowReceivingQrCodeArgs),
    ExportPublicInfo(SinglesigExportPublicInfoArgs),
    SignPsbt(SignPsbtArgs),
    Reencode(SinglesigReencodeArgs),
}

#[derive(clap::Args)]
#[command(about = "Reencode the wallet with new password and other parameters")]
struct MultisigReencodeArgs {
    #[clap(flatten)]
    common: GenerateCommon,
    #[clap(
        help = WALLET_OUTPUT_FILE_HELP
    )]
    wallet_output_file: Option<String>,
}

#[derive(Subcommand)]
enum MultisigOpenCommands {
    ShowSecrets(MultisigShowSecretsArgs),
    ShowReceivingQrCode(ShowReceivingQrCodeArgs),
    ExportPublicInfo(MultisigExportPublicInfoArgs),
    SignPsbt(SignPsbtArgs),
    Reencode(MultisigReencodeArgs),
}

#[derive(Clone, clap::Args)]
struct CommonOpenArgs {
    #[clap(
        long,
        help = KEYFILE_HELP
    )]
    keyfile: Vec<String>,
    #[clap(
        long,
        help = DIFFICULTY_HELP,
        default_value_t = key_derivation::DEFAULT_DIFFICULTY_LEVEL
    )]
    difficulty: KeyDerivationDifficulty,
    #[clap(
        help = INPUT_WALLET_HELP
    )]
    wallet_input_file: String,

    #[clap(
        long,
        env = PASSWORD_ENV,
        help = PASSWORD_HELP
    )]
    password: Option<String>,
}

#[derive(clap::Args)]
#[command(
    arg_required_else_help = true,
    about = "Open a singlesig wallet to make an operation"
)]
struct SinglesigOpenArgs {
    #[clap(flatten)]
    common: CommonOpenArgs,
    #[clap(
        long,
        action,
        help = ENABLE_DURESS_WALLET
    )]
    enable_duress_wallet: bool,
    #[clap(subcommand)]
    command: SinglesigOpenCommands,
}

#[derive(clap::Args)]
#[command(
    arg_required_else_help = true,
    about = "Open a multisig wallet to make an operation"
)]
struct MultisigOpenArgs {
    #[clap(flatten)]
    common: CommonOpenArgs,
    #[clap(short, long, help = "Input wallets to use as signers")]
    input_files: Vec<String>,
    #[clap(subcommand)]
    command: MultisigOpenCommands,
}

#[derive(clap::Args)]
#[command(about = "Generate many encrypted wallets")]
struct SinglesigBatchGenerateExportArgs {
    #[clap(flatten)]
    common: GenerateCommon,
    #[clap(
        long,
        action,
        help = USE_12_WORDS_HELP
    )]
    use_12_words: bool,
    #[clap(
        long,
        action,
        help = ENABLE_DURESS_WALLET
    )]
    enable_duress_wallet: bool,
    #[clap(
        long,
        action,
        help = "Will NOT export the json with the xpub, receiving addresses and other params"
    )]
    disable_public_info_export: bool,
    #[clap(long, help = "How many wallets to generate", default_value = "10")]
    wallets_quantity: usize,
    #[clap(
        help = "Files names will be automatically generated based on this prefix",
        default_value = "wallet"
    )]
    output_prefix: String,
}

#[derive(clap::Args)]
#[command(about = "Interactive mode. Will guide you asking questions")]
struct InteractiveArgs {
    #[clap(
        long,
        help = DIFFICULTY_HELP,
    )]
    difficulty: Option<KeyDerivationDifficulty>,
    #[clap(
        long,
        help = KEYFILE_HELP
    )]
    keyfile: Vec<String>,
    #[clap(
        long,
        action,
        help = ENABLE_DURESS_WALLET
    )]
    enable_duress_wallet: bool,

    #[clap(
        long,
        env = PASSWORD_ENV,
        help = PASSWORD_HELP
    )]
    password: Option<String>,
}

#[derive(clap::Args)]
#[command(about = "Run the key derivation for different difficulty levels and print the duration")]
struct BenchmarkArgs;

#[derive(clap::Args)]
#[command(about = "Shows the version")]
struct VersionArgs;

#[derive(clap::Args)]
#[command(about = "Split a wallet seed into shares using Pedersen secret sharing")]
struct SplitSecretArgs {
    #[clap(flatten)]
    common: CommonOpenArgs,
    #[clap(
        long,
        action,
        help = ENABLE_DURESS_WALLET
    )]
    enable_duress_wallet: bool,
    #[clap(
        long,
        help = "Minimum number of shares needed to reconstruct the secret (M in M-of-N)",
        default_value = "3"
    )]
    threshold: u8,
    #[clap(
        long,
        help = "Total number of shares to create (N in M-of-N)",
        default_value = "5"
    )]
    total_shares: u8,
    #[clap(
        long,
        help = "Directory where share files will be written",
        default_value = "."
    )]
    output_dir: String,
    #[clap(
        long,
        action,
        help = "Disable all padding for share files. WARNING: File size may leak information about wallet contents"
    )]
    disable_all_padding: bool,
    #[clap(
        long,
        default_value_t = DEFAULT_MIN_ADDITIONAL_PADDING
    )]
    min_additional_padding_bytes: u32,
    #[clap(
        long,
        default_value_t = DEFAULT_MAX_ADDITIONAL_PADDING
    )]
    max_additional_padding_bytes: u32,
    // No `--wallet-file-type` here: VSS share files are always written
    // in the standard format. The compact format cannot be decrypted
    // by `combine-secret`, so accepting it as an option would just
    // promise a value that always errors. Forcing the Standard value
    // unconditionally keeps the help output honest.
    //
    // The flags below let the user encrypt the share files with a
    // *different* credential set than the source wallet was opened with.
    // Common case: the source wallet has password X (which was just used
    // to decrypt it), but you want to give shares to N different
    // recipients each protected under a separate share password Y. If
    // any of these are unset we fall back to the corresponding common
    // open flag, so the existing single-credential workflow keeps
    // working unchanged.
    #[clap(
        long,
        env = "FROZENKRILL_SHARE_PASSWORD",
        help = "Password used to encrypt the share files. Defaults to the same password used to open the source wallet."
    )]
    share_password: Option<String>,
    #[clap(
        long,
        help = "Keyfile(s) used (alongside --share-password) to encrypt the share files. Defaults to the wallet-open --keyfile values when unset. Use --no-share-keyfile to force shares to be encrypted without any keyfiles even when the wallet was opened with one."
    )]
    share_keyfile: Vec<String>,
    #[clap(
        long,
        action,
        conflicts_with = "share_keyfile",
        help = "Encrypt the share files without any keyfiles, even if the source wallet was opened with --keyfile. Use this to produce password-only shares from a keyfile-protected wallet."
    )]
    no_share_keyfile: bool,
    #[clap(
        long,
        help = "KDF difficulty for the share-encryption key. Defaults to the wallet-open --difficulty when unset."
    )]
    share_difficulty: Option<KeyDerivationDifficulty>,
}

#[derive(clap::Args)]
#[command(about = "Combine shares to reconstruct a wallet seed")]
struct CombineSecretArgs {
    #[clap(help = "Paths to share files or directories containing share files")]
    share_paths: Vec<String>,
    /// Kept for backwards compatibility — the recovered mnemonic is now
    /// printed unconditionally, since the only point of `combine-secret`
    /// is to surface the seed for the user to act on.
    #[clap(
        long,
        action,
        hide = true,
        help = "Deprecated: the mnemonic is always displayed on success."
    )]
    display_mnemonic: bool,
    #[clap(
        long,
        help = KEYFILE_HELP
    )]
    keyfile: Vec<String>,
    #[clap(
        long,
        help = DIFFICULTY_HELP,
        default_value_t = key_derivation::DEFAULT_DIFFICULTY_LEVEL
    )]
    difficulty: KeyDerivationDifficulty,
    /// Password to decrypt the share files. We deliberately do NOT
    /// bind a clap `env` here so an explicit `--password ...` cleanly
    /// overrides any environment variables on the same invocation.
    /// Env-based fallback is handled at the call site, in this
    /// priority: explicit --password, then FROZENKRILL_SHARE_PASSWORD env,
    /// then interactive prompt. The generic PASSWORD env (used by other
    /// wallet-open commands) is intentionally NOT consulted here —
    /// shares carry their own credentials (see `--share-password`)
    /// that may legitimately differ from the source wallet's
    /// password, and silently inheriting PASSWORD would turn a
    /// keyfile-only share recovery (empty share password) into a
    /// confusing "wrong password" loop. For empty-password shares,
    /// pass `--password ""` explicitly.
    #[clap(
        long,
        help = "Password to decrypt the share files. Explicit --password overrides the FROZENKRILL_SHARE_PASSWORD env var; if neither is set you'll be prompted interactively (which accepts empty input for keyfile-only share sets). The generic PASSWORD env is NOT consulted here — shares have their own credentials separate from the source wallet's password."
    )]
    password: Option<String>,
}

#[derive(Subcommand)]
enum Commands {
    Interactive(InteractiveArgs),
    SinglesigGenerate(SinglesigGenerateArgs),
    MultisigGenerate(MultisigGenerateArgs),
    SinglesigOpen(SinglesigOpenArgs),
    MultisigOpen(MultisigOpenArgs),
    SinglesigBatchGenerateExport(SinglesigBatchGenerateExportArgs),
    SplitSecret(SplitSecretArgs),
    CombineSecret(CombineSecretArgs),
    Benchmark(BenchmarkArgs),
    Version(VersionArgs),
}

const ABOUT: &str = "
frozenkrill: A minimalist Bitcoin wallet focused on cold storage

A cold storage wallet is used to receive and store bitcoins without a connection to internet.
This wallet is composed of the seeds (12 or 24 words) strongly encrypted with brute-force resistant algorithms and parameters.
If a keyfile and a strong password is used, it's possible to save the wallet file in relatively unsafe storage system (like cloud providers, email or with friends).

For maximum security, it's recommended to only generate and decrypt the wallet in a offline computer with a minimalist open-source Unix distribution (Linux/BSD).

Start with the 'interactive' command";

#[derive(Parser)]
#[command(about = ABOUT)]
struct Cli {
    #[clap(short, long, action, help = "Don't show 'info' messages")]
    quiet: bool,

    #[clap(
        long,
        action,
        help = "Will disable internet connectivity check (dangerous!)"
    )]
    disable_internet_check: bool,

    #[clap(long, help = "Use a less colorful theme for prompts")]
    use_simple_theme: bool,

    #[clap(subcommand)]
    command: Commands,
}

const ENGLISH: Language = Language::English;
const RUST_LOG: &str = "RUST_LOG";

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    // Initialize logger with appropriate level
    if std::env::var(RUST_LOG).is_ok() {
        // If RUST_LOG is set, use it and warn if --quiet was also used
        if cli.quiet {
            eprintln!(
                "Warning: the {RUST_LOG} environment variable will override the --quiet flag"
            );
        }
        custom_logger::init();
    } else {
        // RUST_LOG not set, use our own level based on quiet flag
        let log_level = if cli.quiet { "warn" } else { "info" };
        custom_logger::init_with_level(log_level);
    }

    let (term, theme) = get_term_theme(cli.use_simple_theme);
    #[cfg(windows)]
    {
        log::error!("You're using Windows");
        bail!("Don't be reckless, use a safer operating system")
    };
    #[cfg(not(unix))]
    bail!(
        "This isn't a Unix-like operating system. As this is a untested setup, better contact the developers"
    );
    match process(cli, theme, &term) {
        Ok(()) => Ok(()),
        Err(e) => {
            reset_terminal(&term);
            Err(e)
        }
    }
}

fn process(cli: Cli, theme: Box<dyn Theme>, term: &Term) -> Result<(), anyhow::Error> {
    let mut rng = rand::thread_rng();
    let mut secp = get_secp(&mut rng);
    let ic = InternetCheckerImpl::new(cli.disable_internet_check);
    match cli.command {
        Commands::SinglesigGenerate(args) => {
            commands::generate::singlesig_generate(
                theme.as_ref(),
                term,
                &mut secp,
                &mut rng,
                ic,
                args,
            )?;
        }
        Commands::MultisigGenerate(args) => {
            commands::generate::multisig_generate(
                theme.as_ref(),
                term,
                &mut secp,
                &mut rng,
                ic,
                args,
            )?;
        }
        Commands::SinglesigOpen(open_args) => match &open_args.command {
            SinglesigOpenCommands::ShowSecrets(args) => {
                commands::show_secrets::singlesig_show_secrets_parse_args(args)?;
                let (wallet, non_duress_password) = open_singlesig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                )?;
                commands::show_secrets::singlesig_show_secrets(
                    theme.as_ref(),
                    term,
                    &secp,
                    &wallet,
                    &non_duress_password,
                )?;
            }
            SinglesigOpenCommands::ExportPublicInfo(args) => {
                let (output_file_path, address_generation_params) =
                    commands::export_public_info::export_public_info_parse_args(
                        &open_args.common,
                        &args.common,
                    )?;
                let (wallet, non_duress_password) = open_singlesig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                )?;
                let non_duress_output_file_json = args
                    .non_duress_output_file_json
                    .as_ref()
                    .map(handle_output_path)
                    .transpose()?
                    .map(|p| p.to_path_buf());
                let duress_params = match non_duress_password {
                    Some(non_duress_password) => calculate_non_duress_output(
                        true,
                        &non_duress_output_file_json,
                        &Some(output_file_path.clone()),
                    )?
                    .map(
                        |non_duress_public_info_json_output| DuressPublicInfoParams {
                            non_duress_password: Arc::clone(&non_duress_password),
                            non_duress_public_info_json_output,
                        },
                    ),
                    None => None,
                };
                commands::export_public_info::export_singlesig(
                    theme.as_ref(),
                    term,
                    &secp,
                    &wallet,
                    &output_file_path,
                    &duress_params,
                    &address_generation_params,
                )?;
            }
            SinglesigOpenCommands::ShowReceivingQrCode(args) => {
                let (amount, address_index) =
                    commands::show_receiving_qr_code::show_receiving_qr_code_parse_args(args)?;
                let (wallet, non_duress_password) = open_singlesig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                )?;
                commands::show_receiving_qr_code::singlesig_show_receiving_qr_code(
                    theme.as_ref(),
                    term,
                    &secp,
                    &wallet,
                    amount,
                    address_index,
                    &non_duress_password,
                )?;
            }
            SinglesigOpenCommands::SignPsbt(args) => {
                commands::psbt::singlesig_sign_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                    args,
                )?;
            }
            SinglesigOpenCommands::Reencode(args) => {
                let core_args =
                    commands::reencode::singlesig_reencode_parse_args(&open_args, args)?;
                // FIXME: should we ask/use non duress password here?
                let (wallet, _non_duress_password) = open_singlesig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic.clone(),
                    &open_args,
                )?;

                commands::reencode::singlesig_core_reencode(
                    theme.as_ref(),
                    term,
                    &mut secp,
                    &mut rng,
                    ic,
                    &wallet,
                    core_args,
                )?;
            }
        },
        Commands::MultisigOpen(open_args) => match &open_args.command {
            MultisigOpenCommands::ShowSecrets(_) => {
                let wallet = open_multisig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                )?;
                commands::show_secrets::multisig_show_secrets(&secp, &wallet)?;
            }
            MultisigOpenCommands::ShowReceivingQrCode(args) => {
                let (amount, address_index) =
                    commands::show_receiving_qr_code::show_receiving_qr_code_parse_args(args)?;
                let wallet = open_multisig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                )?;
                commands::show_receiving_qr_code::multisig_show_receiving_qr_code(
                    &secp,
                    &wallet,
                    amount,
                    address_index,
                )?;
            }
            MultisigOpenCommands::ExportPublicInfo(args) => {
                let (output_file_path, address_generation_params) =
                    commands::export_public_info::export_public_info_parse_args(
                        &open_args.common,
                        &args.common,
                    )?;
                let wallet = open_multisig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                )?;
                commands::export_public_info::export_multisig(
                    &secp,
                    &wallet,
                    &output_file_path,
                    &address_generation_params,
                )?;
            }
            MultisigOpenCommands::SignPsbt(args) => {
                commands::psbt::multisig_sign_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                    args,
                )?;
            }
            MultisigOpenCommands::Reencode(args) => {
                let core_args = commands::reencode::multisig_reencode_parse_args(&open_args, args)?;
                let wallet = open_multisig_wallet_non_interactive(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic.clone(),
                    &open_args,
                )?;
                commands::reencode::multisig_core_reencode(
                    theme.as_ref(),
                    term,
                    &mut secp,
                    &mut rng,
                    ic,
                    &wallet,
                    core_args,
                )?;
            }
        },
        Commands::SinglesigBatchGenerateExport(args) => {
            commands::batch_generate_export::batch_generate_export(
                theme.as_ref(),
                term,
                &mut secp,
                &mut rng,
                ic,
                &args,
            )?
        }
        Commands::SplitSecret(args) => {
            // VSS share files are always written in the standard format —
            // there is no `--wallet-file-type` flag here.

            // Run the offline-only safety gate BEFORE we ask the user
            // for any credentials. The wallet password and (in duress
            // mode) the BIP-39 passphrase are sensitive secrets; the
            // user shouldn't be prompted to type them on a connected
            // host that we'd then refuse anyway. This mirrors the
            // open/show-secrets flows.
            let mut ic = ic;
            ic.check()?;

            // Validate cheap CLI inputs (M-of-N pair, output dir,
            // padding range) BEFORE asking for any secret. Otherwise
            // a command that's guaranteed to fail downstream would
            // still collect the wallet password and (in duress mode)
            // the BIP-39 passphrase from the user.
            anyhow::ensure!(
                args.threshold >= 2 && args.total_shares >= 2,
                "Threshold and total shares must each be at least 2 (got threshold={}, total_shares={})",
                args.threshold,
                args.total_shares
            );
            anyhow::ensure!(
                args.threshold <= args.total_shares,
                "Threshold ({}) cannot exceed total shares ({})",
                args.threshold,
                args.total_shares
            );
            let preflight_output_dir = std::path::Path::new(&args.output_dir);
            anyhow::ensure!(
                preflight_output_dir.exists(),
                "Output directory does not exist: {}",
                preflight_output_dir.display()
            );
            anyhow::ensure!(
                preflight_output_dir.is_dir(),
                "Output path is not a directory: {}",
                preflight_output_dir.display()
            );
            anyhow::ensure!(
                args.min_additional_padding_bytes <= args.max_additional_padding_bytes,
                "min_additional_padding_bytes ({}) must be <= max_additional_padding_bytes ({})",
                args.min_additional_padding_bytes,
                args.max_additional_padding_bytes
            );
            // Preflight the source wallet path too, so a missing /
            // unreadable input file is rejected before we collect any
            // secrets. The downstream open path would error eventually
            // either way, but only after `ask_password` (and, in
            // duress mode, the BIP-39 passphrase prompt) had run.
            let preflight_wallet_input = std::path::Path::new(&args.common.wallet_input_file);
            anyhow::ensure!(
                preflight_wallet_input.exists(),
                "Source wallet file does not exist: {}",
                preflight_wallet_input.display()
            );
            anyhow::ensure!(
                preflight_wallet_input.is_file(),
                "Source wallet path is not a file: {}",
                preflight_wallet_input.display()
            );

            // Pre-resolve the share-keyfile paths (if explicitly
            // supplied) so unreadable / mistyped paths fail BEFORE we
            // ask the user for any secret. The result is then reused
            // by the share-encryption path further down without
            // re-parsing.
            let preflight_share_keyfiles: Option<Vec<PathBuf>> =
                if args.no_share_keyfile || args.share_keyfile.is_empty() {
                    None
                } else {
                    Some(parse_keyfiles_paths(&args.share_keyfile)?)
                };

            // Show the M-of-N risk warning and require confirmation
            // BEFORE we ask the user for any secret. If they cancel at
            // the warning, we don't want to have already prompted for
            // (and held in memory) the wallet password and — in duress
            // mode — the BIP-39 passphrase. Putting the prompt here
            // also means a typo / cancel costs zero credential entry.
            println!("\n⚠️  WARNING: Secret Sharing Operation");
            println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
            println!(
                "You are about to split your wallet seed into {} shares.",
                args.total_shares
            );
            println!(
                "You will need at least {} shares to reconstruct the seed.",
                args.threshold
            );
            println!("\nIMPORTANT SECURITY NOTES:");
            println!("  • Store each share in a SEPARATE, SECURE location");
            println!(
                "  • Losing {} or more shares = PERMANENT LOSS of funds",
                args.total_shares - args.threshold + 1
            );
            println!(
                "  • Anyone with {} or more shares can access your wallet",
                args.threshold
            );
            println!(
                "  • Shares will be written to: {}",
                preflight_output_dir.display()
            );
            println!("  • This operation is IRREVERSIBLE");
            println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

            let confirmed = Confirm::with_theme(theme.as_ref())
                .with_prompt("Do you understand the risks and want to proceed?")
                .default(false)
                .interact_on(term)?;

            if !confirmed {
                println!("Operation cancelled by user.");
                return Ok(());
            }

            // Parse keyfiles and get password before opening wallet.
            // We need the password for both opening and encrypting shares,
            // so keep it in the `SecretString` wrapper end-to-end rather
            // than round-tripping through a plain `String` (which would
            // leave a non-zeroizing copy on the heap until the open
            // completes).
            //
            // We deliberately do NOT use the global `ask_password()`
            // helper here. That helper requires a confirmation re-entry
            // and rejects empty input — both correct for *creating*
            // credentials, both wrong for *entering existing* ones.
            // In particular, a wallet created keyfile-only (empty
            // password + one or more keyfiles) is a valid configuration
            // supported by the rest of the CLI via `--password ""`;
            // the interactive split-secret flow must be able to open
            // that wallet too. Allowing empty input here mirrors what
            // `combine-secret` does when prompting for the share
            // decryption credential.
            let keyfiles = parse_keyfiles_paths(&args.common.keyfile)?;
            let password = match args.common.password.clone() {
                Some(p) => Arc::new(SecretString::new(p.into())),
                None => {
                    let typed = dialoguer::Password::with_theme(theme.as_ref())
                        .with_prompt(
                            "Source wallet password (leave blank for keyfile-only wallets)",
                        )
                        .allow_empty_password(true)
                        .interact_on(term)
                        .context("failure reading source wallet password")?;
                    Arc::new(SecretString::new(typed.into()))
                }
            };

            // Build the open args without the password field; we pass the
            // already-wrapped SecretString in directly.
            //
            // We deliberately set `enable_duress_wallet: false` on the
            // open args even when the user passed `--enable-duress-wallet`.
            // The shared `singlesig_core_open` path forwards duress mode
            // into `ask_non_duress_password`, which requires a non-empty
            // passphrase — and split-secret needs to allow Enter-to-skip
            // (an empty passphrase = no duress mode). We instead ask
            // separately here with `ask_optional_non_duress_password`,
            // which accepts empty input cleanly and returns `None` in
            // that case.
            let open_args = SinglesigOpenArgs {
                common: CommonOpenArgs {
                    keyfile: args.common.keyfile.clone(),
                    difficulty: args.common.difficulty,
                    wallet_input_file: args.common.wallet_input_file.clone(),
                    password: None,
                },
                enable_duress_wallet: false,
                command: SinglesigOpenCommands::ShowSecrets(SinglesigShowSecretsArgs {
                    acknowledge_dangerous_operation: true, // Internal call, we know what we're doing
                }),
            };

            let (wallet, _no_passphrase) =
                commands::common::singlesig::open_singlesig_wallet_non_interactive_with_password(
                    theme.as_ref(),
                    term,
                    &secp,
                    ic,
                    &open_args,
                    Some(Arc::clone(&password)),
                )?;
            let non_duress_password = if args.enable_duress_wallet {
                ask_optional_non_duress_password(theme.as_ref(), term)?
            } else {
                None
            };

            // Duress-mode handling. The decoy wallet and the real wallet
            // share the *same* BIP-39 mnemonic — the only difference is the
            // BIP-39 passphrase, which is mixed in at seed-derivation time
            // and is *not* part of the mnemonic itself. So splitting the
            // decoy wallet's mnemonic produces shares that, when combined,
            // reconstruct that same mnemonic — which is also the real
            // wallet's mnemonic. The user only needs the BIP-39 passphrase
            // (from memory) to switch from the decoy view to the real view.
            //
            // Critically, we keep the share-file `original_wallet` metadata
            // pinned to the *decoy* wallet here. The shares are encrypted
            // with the same wallet password the user typed at the prompt,
            // and in a coercion scenario that password is precisely what
            // the attacker is most likely to obtain. If the embedded
            // metadata described the real wallet (xpub, addresses, …), a
            // single decrypted share would let a coerced attacker prove the
            // hidden wallet exists — defeating plausible deniability. With
            // decoy metadata, an attacker who decrypts a share sees only
            // the decoy.
            //
            // We still ask for, and double-check, the non-duress passphrase
            // to make sure the user actually knows it (otherwise they would
            // be locked out of the real wallet without realizing it),
            // because once the shares are written they cannot be amended.
            // Whether THIS split is in duress mode: yes iff the user
            // supplied a *non-empty* non-duress passphrase. BIP-39
            // treats an empty passphrase as the normal wallet, so just
            // pressing Enter at the duress prompt should NOT mark the
            // shares as duress (otherwise recovery would later refuse
            // to open them as a normal share, and the duress warning
            // would mislead the user). The flag gets baked into each
            // share's metadata so that `combine-secret` / `to_singlesig`
            // can later require/refuse a passphrase appropriately at
            // restore time.
            let is_duress_split = non_duress_password
                .as_ref()
                .is_some_and(|p| !p.expose_secret().is_empty());
            if is_duress_split && let Some(non_duress_password) = non_duress_password.as_ref() {
                commands::common::double_check_non_duress_password(
                    theme.as_ref(),
                    term,
                    non_duress_password,
                )?;

                // Derive the wallet that the user's typed passphrase
                // would actually open and show its first address. Then
                // require the user to confirm it's the wallet they
                // think they're backing up. Without this check, a
                // *consistent typo* on the duress passphrase passes the
                // double-check above but produces shares for the wrong
                // hidden wallet — funds behind the real passphrase
                // would never be backed up. There's no on-disk witness
                // for the hidden wallet (by design, for plausible
                // deniability), so visual confirmation against the
                // user's own knowledge of their funded address is the
                // only check available.
                let candidate_real =
                    wallet.change_seed_password(&Some(Arc::clone(non_duress_password)), &secp)?;
                let candidate_first_address =
                    candidate_real.first_receiving_address(&secp)?.to_string();
                println!("\n⚠️  CONFIRM HIDDEN-WALLET ADDRESS");
                println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
                println!("Using the non-duress passphrase you just typed, the hidden");
                println!("wallet's first receiving address is:");
                println!();
                println!("    {candidate_first_address}");
                println!();
                println!("If this is NOT the wallet you intend to back up (e.g. the");
                println!("address does not match the funded wallet you think you have");
                println!("behind your duress passphrase), the passphrase you typed is");
                println!("wrong and these shares would silently strand those funds.");
                println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
                let confirmed = Confirm::with_theme(theme.as_ref())
                    .with_prompt("Is this the hidden wallet you want to back up with these shares?")
                    .default(false)
                    .interact_on(term)?;
                if !confirmed {
                    anyhow::bail!(
                        "User did not confirm the hidden-wallet address — refusing to write \
                         duress-mode shares that may not back up the intended wallet"
                    );
                }
                drop(candidate_real);

                println!("\n⚠️  DURESS-MODE BACKUP NOTE");
                println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
                println!("Each share file embeds DECOY-wallet metadata only — that is");
                println!("intentional. If a coerced attacker learns the wallet password");
                println!("they can decrypt one share and see only the decoy's xpub and");
                println!("first address, never the real wallet's identity.");
                println!();
                println!("The split shares back up the SEED, which is the SAME for the");
                println!("decoy and the real wallet. To restore the real wallet you must");
                println!("(a) reconstruct the seed via `combine-secret`, AND");
                println!("(b) supply the non-duress BIP-39 passphrase from memory.");
                println!("`combine-secret` plus the shares alone yield the decoy view.");
                println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
            }
            // Use the decoy wallet (`wallet` as returned above) for both
            // splitting and metadata embedding. We deliberately do NOT call
            // `change_seed_password` here.

            // Create padding params
            let padding_params = PaddingParams::new(
                args.disable_all_padding,
                Some(args.min_additional_padding_bytes),
                Some(args.max_additional_padding_bytes),
            )?;

            // VSS share files are always V0Standard.
            let encrypted_version = EncryptedWalletVersion::V0Standard;

            // Resolve the share-encryption credentials. Default to the
            // wallet-open credentials so the existing single-credential
            // workflow keeps working unchanged. Override when any of the
            // `--share-*` flags is set. `--no-share-keyfile` is the
            // explicit way to say "shares use no keyfiles even though
            // the wallet did" — needed because an empty
            // `--share-keyfile` would otherwise be indistinguishable
            // from the user not passing it at all.
            let share_keyfiles = if args.no_share_keyfile {
                Vec::new()
            } else if let Some(prevalidated) = preflight_share_keyfiles {
                prevalidated
            } else {
                keyfiles.clone()
            };
            let share_password = match args.share_password.clone() {
                Some(p) => Arc::new(SecretString::new(p.into())),
                None => Arc::clone(&password),
            };
            let share_difficulty = args.share_difficulty.unwrap_or(args.common.difficulty);

            // Split the wallet
            let output_dir = std::path::PathBuf::from(&args.output_dir);
            commands::split_secret::split_singlesig_wallet(
                &secp,
                &wallet,
                args.threshold,
                args.total_shares,
                &output_dir,
                &share_password,
                &share_keyfiles,
                share_difficulty,
                &padding_params,
                encrypted_version,
                is_duress_split,
                &mut rng,
            )?;
        }
        Commands::CombineSecret(args) => {
            // combine-secret reconstructs and prints the seed phrase, so
            // it has to honor the project-wide offline-only safety gate
            // just like every other command that exposes secrets
            // (`open ... show-secrets`, `singlesig-generate`, …). Run
            // `InternetChecker::check()` BEFORE we decrypt any shares
            // so the user can't accidentally reveal a recovered seed
            // on an internet-connected machine.
            let mut ic = ic;
            ic.check()?;
            let keyfiles = parse_keyfiles_paths(&args.keyfile)?;
            // Resolve the share-decryption password in this priority:
            //   1. Explicit `--password` on the CLI (args.password).
            //      We deliberately don't bind clap's `env` for this
            //      arg so an explicit override always wins.
            //   2. FROZENKRILL_SHARE_PASSWORD env, the same one
            //      `split-secret --share-password` reads.
            //   3. Interactive prompt (handled inside combine_shares,
            //      which accepts empty input for keyfile-only shares).
            //
            // We intentionally do NOT fall back to the generic
            // PASSWORD env here. That variable is the wallet-open
            // credential for other Frozenkrill commands and may be
            // set in a shell where the user is recovering shares
            // that were written keyfile-only (empty share password).
            // Inheriting PASSWORD as the share password would silently
            // turn every share decryption into a "wrong password"
            // error and never reach the interactive empty-password
            // prompt, breaking the keyfile-only recovery flow with
            // no useful diagnostic.
            let password = args
                .password
                .clone()
                .or_else(|| std::env::var("FROZENKRILL_SHARE_PASSWORD").ok())
                .map(|p| SecretString::new(p.into()));
            commands::combine_secret::combine_shares(
                theme.as_ref(),
                term,
                &args.share_paths,
                args.display_mnemonic,
                &keyfiles,
                args.difficulty,
                password,
            )?;
        }
        Commands::Interactive(args) => commands::interactive::interactive(
            theme.as_ref(),
            term,
            &mut secp,
            &mut rng,
            ic,
            &args,
        )?,
        Commands::Benchmark(_) => commands::benchmark()?,
        Commands::Version(_) => eprintln!("frozenkrill {VERSION}"),
    };
    Ok(())
}

#[derive(Clone)]
pub(crate) struct InternetCheckerImpl {
    h: Arc<Mutex<Option<JoinHandle<bool>>>>,
    is_connected: Option<bool>,
}

pub(crate) trait InternetChecker: Clone {
    fn check(&mut self) -> anyhow::Result<()>;
}

mockall::mock! {
    InternetChecker {}     // Name of the mock struct, less the "Mock" prefix
    impl Clone for InternetChecker {   // specification of the trait to mock
        fn clone(&self) -> Self;
    }

    impl InternetChecker for InternetChecker {   // specification of the trait to mock
        fn check(&mut self) -> anyhow::Result<()>;
    }
}

impl InternetCheckerImpl {
    pub(crate) fn new(disable_check: bool) -> Self {
        if disable_check {
            log::warn!("Will proceed without checking if the device is connected to internet");
            log::warn!("Only do this for testing or on exceptional circumstances");
            Self {
                h: Arc::new(Mutex::new(None)),
                is_connected: None,
            }
        } else {
            Self {
                h: Arc::new(Mutex::new(Some(std::thread::spawn({
                    move || {
                        use std::net::ToSocketAddrs;
                        {
                            let i = "github.com";
                            match format!("{i}:443").to_socket_addrs() {
                                Ok(mut v) => {
                                    if v.next().is_some() {
                                        log::debug!("this is bad: {i} is reachable");
                                        return true;
                                    } else {
                                        log::debug!(
                                            "this is good, {i} is unreachable because returned iterator is empty"
                                        );
                                    }
                                }
                                Err(e) => log::debug!("this is good, {i} is unreachable: {e:?}"),
                            };
                        }
                        false
                    }
                })))),
                is_connected: None,
            }
        }
    }
}

impl InternetChecker for InternetCheckerImpl {
    fn check(&mut self) -> anyhow::Result<()> {
        if let Some(h) = self.h.lock().expect("to lock").take() {
            if !h.is_finished() {
                log::info!("Making sure internet is disconnected...")
            }
            let is_connected = h.join().expect("to join");
            self.is_connected = Some(is_connected);
            if is_connected {
                log::error!("You are connected to internet");
                eprintln!("This software should only be used in offline devices");
                eprintln!("Disconnect from internet and try again");
                eprintln!(
                    "Or use `frozenkrill --disable-internet-check` if you know what you're doing"
                );
                bail!("Internet is reachable")
            } else {
                Ok(())
            }
        } else if self.is_connected.unwrap_or_default() {
            bail!("Internet is reachable")
        } else {
            Ok(())
        }
    }
}

fn reset_terminal(term: &Term) {
    // TODO: fully restore terminal
    term.show_cursor().expect("to show cursor");
}

fn get_term_theme(use_simple_theme: bool) -> (Term, Box<dyn Theme>) {
    let theme: Box<dyn Theme> = if use_simple_theme {
        Box::new(SimpleTheme {})
    } else {
        Box::<ColorfulTheme>::default()
    };
    let term = Term::stderr(); // TODO: change to buffered_stderr when master get fixes
    (term, theme)
}

fn ask_password(theme: &dyn Theme, term: &Term) -> anyhow::Result<SecretString> {
    Ok(SecretString::new(
        dialoguer::Password::with_theme(theme)
            .with_prompt("Password")
            .with_confirmation("Confirm password", "Passwords don't match, try again")
            .allow_empty_password(false)
            .interact_on(term)
            .context("failure reading password")?
            .into(),
    ))
}

fn ask_non_duress_password(theme: &dyn Theme, term: &Term) -> anyhow::Result<Arc<SecretString>> {
    // The global non-duress prompt requires a non-empty passphrase:
    // the existing duress-wallet flows (generate, open) need it to
    // genuinely differ from the decoy. `split-secret` has its own
    // local prompt (`ask_optional_non_duress_password`) that accepts
    // empty input and translates that into "no duress mode".
    Ok(Arc::new(SecretString::new(
        dialoguer::Password::with_theme(theme)
            .with_prompt("Enter a non duress seed password")
            .with_confirmation("Confirm password", "Passwords don't match, try again")
            .interact_on(term)
            .context("failure reading password")?
            .into(),
    )))
}

/// Variant of `ask_non_duress_password` used by `split-secret` only.
/// Accepts empty input and returns `None` in that case. The caller
/// then treats `None` as "the user does not want duress mode for this
/// split", and writes normal (non-duress) shares.
fn ask_optional_non_duress_password(
    theme: &dyn Theme,
    term: &Term,
) -> anyhow::Result<Option<Arc<SecretString>>> {
    let typed = dialoguer::Password::with_theme(theme)
        .with_prompt("Enter the non-duress BIP-39 passphrase (leave blank if the wallet has none)")
        .allow_empty_password(true)
        .with_confirmation("Confirm passphrase", "Passphrases don't match, try again")
        .interact_on(term)
        .context("failure reading passphrase")?;
    if typed.is_empty() {
        Ok(None)
    } else {
        Ok(Some(Arc::new(SecretString::new(typed.into()))))
    }
}

pub(crate) fn get_derivation_key_spinner() -> ProgressBar {
    get_spinner("Deriving encryption keys from password and salt... please be patient")
}

fn warn_difficulty_level(difficulty: &KeyDerivationDifficulty) {
    if difficulty == &KeyDerivationDifficulty::Easy {
        log::warn!("The 'easy' difficulty level should only be used for testing");
        log::warn!("Or if you are very confident of your password and keyfiles strength");
    }
}

fn ui_derive_key(
    password: &SecretString,
    keyfiles: &[PathBuf],
    salt: &[u8; SALT_SIZE],
    difficulty: &KeyDerivationDifficulty,
) -> anyhow::Result<Secret<[u8; KEY_SIZE]>> {
    log::info!(
        "Using difficulty = {difficulty:?} ({}, {})",
        difficulty.estimate_time(),
        difficulty.estimate_memory()
    );
    log::info!("The above time is an estimate for modern cpus");
    log::info!("It may take much longer on some platforms");
    log::info!("This is our main protection against brute force attacks");
    let pb = get_derivation_key_spinner();
    let now = Instant::now();
    let key = default_derive_key(password, keyfiles, salt, difficulty).context("failure deriving key, check if you have enough memory, perhaps try with a easier --difficulty param")?;
    pb.finish_with_message(format!(
        "Key derivation finished in {:?}s",
        now.elapsed().as_secs()
    ));
    Ok(key)
}

fn handle_input_path(input_file: &str) -> anyhow::Result<Cow<'_, Path>> {
    let input_file_path = Path::new(input_file);
    anyhow::ensure!(
        input_file_path.exists(),
        "The given file {input_file_path:?} doesn't exists"
    );
    Ok(input_file_path.absolutize()?)
}

fn handle_output_path<S: AsRef<std::ffi::OsStr> + ?Sized>(
    output_file: &S,
) -> anyhow::Result<Cow<'_, Path>> {
    let output_file_path = Path::new(output_file);
    anyhow::ensure!(
        !output_file_path.exists(),
        "The output file {output_file_path:?} already exists, delete it or change the name"
    );
    Ok(output_file_path.absolutize()?)
}

fn ui_ask_manually_seed_input(
    rng: &mut (impl CryptoRng + frozenkrill_core::rand::RngCore),
    theme: &dyn Theme,
    term: &Term,
    word_count: &WordCount,
    always_hide_typed_seed: bool,
) -> anyhow::Result<Secret<Mnemonic>> {
    let total_words = word_count.to_integer();
    let will_fill_everything = dialoguer::Select::with_theme(theme)
        .with_prompt("Pick an option for the custom seed")
        .item(format!("I will manually input all {total_words} words"))
        .item(format!(
            "I will fill {} words and let the last word be automatically calculated (checksum)",
            total_words - 1
        ))
        .default(0)
        .interact_on(term)?
        == 0;
    let words_to_ask = if will_fill_everything {
        total_words
    } else {
        total_words - 1
    };
    let english = ENGLISH;
    let show_seeds_history = will_fill_everything && !always_hide_typed_seed;
    let word_list = english.word_list();
    let fuzzy_select = dialoguer::FuzzySelect::with_theme(theme)
        .items(word_list)
        .default(0)
        .report(show_seeds_history)
        .max_length(10);
    loop {
        let mut words = Vec::with_capacity(total_words.into());
        for i in 1..=words_to_ask {
            let word_index = fuzzy_select
                .clone()
                .with_prompt(format!("Start typing... (word {i} of {words_to_ask})"))
                .interact_on(term)?;
            let word = word_list[word_index];
            words.push(word.to_owned());
        }
        if !will_fill_everything {
            words = mnemonic_utils::complete_words_with_checksum(rng, &words)?;
        }
        match Mnemonic::from_str(&words.join(" ")) {
            Ok(mnemonic) => return Ok(Secret::from(Box::new(mnemonic))),
            Err(bip39::Error::InvalidChecksum) => {
                if !dialoguer::Confirm::with_theme(theme)
                    .with_prompt("The checksum is invalid. A word must be incorrect. Try again?")
                    .interact_on(term)?
                {
                    bail!("Aborting because of invalid seed");
                }
            }
            Err(e) => Err(e)?,
        }
    }
}

fn ui_get_singlesig_wallet_description(
    json_wallet_description: &Secret<SinglesigJsonWalletDescriptionV0>,
    seed_password: &Option<Arc<SecretString>>,
    secp: &Secp256k1<All>,
) -> anyhow::Result<SingleSigWalletDescriptionV0> {
    let w = json_wallet_description
        .expose_secret()
        .to(seed_password, secp)
        .context("failure parsing generated wallet")?;
    match SinglesigJsonWalletDescriptionV0::validate_same(json_wallet_description, &w, secp)? {
        Ok(()) => Ok(w),
        Err(e) => bail!("Validation error: {e:?}"),
    }
}
